# Generated by Django 4.0.2 on 2022-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='n/a', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='n/a', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='job_type',
            field=models.CharField(default='n/a', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
