# Generated by Django 4.0.2 on 2022-02-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='n/a', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_type',
            field=models.CharField(default='all', max_length=30),
        ),
    ]
