# Generated by Django 4.0.2 on 2022-02-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_title', models.CharField(max_length=30)),
                ('job_type', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
