# Generated by Django 4.0.2 on 2022-02-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_details',
            field=models.CharField(default='n/a', max_length=30),
        ),
    ]
