# Generated by Django 4.0.2 on 2022-02-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_job_job_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_list',
            fields=[
                ('job_title', models.CharField(max_length=30)),
                ('job_type', models.CharField(max_length=30)),
                ('job_details', models.CharField(default='n/a', max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default='0')),
            ],
        ),
    ]
