# Generated by Django 4.0.2 on 2022-02-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_job_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_list',
            name='user_id',
        ),
    ]
