# Generated by Django 4.0.2 on 2022-02-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_company_email_company_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_id',
            field=models.IntegerField(default='0'),
        ),
    ]
