# Generated by Django 4.0.2 on 2022-02-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_job_list_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_list',
            name='company_id',
            field=models.IntegerField(default='0'),
        ),
    ]
